%% Interactive Viewer for Bremsstrahlung LUT (Fixed)
% Adds sliders for Velocity (v), Pitch Angle (theta), and Observation Angle (alpha).
% Requires: 'Bremsstrahlung_LUT.mat' (generated by the simulation code)

clear; close all; clc;

% --- 1. Load Data ---
filename = 'Bremsstrahlung_LUT.mat';
if ~isfile(filename)
    error('File %s not found. Please run the simulation code first.', filename);
end
fprintf('Loading %s ...\n', filename);
load(filename);
% Loaded vars: LUT_Emissivity, w_grid, alpha_grid, theta_p_grid, v_grid
% LUT dimensions: (w, alpha, theta, v)

[Nw, Na, Nt, Nv] = size(LUT_Emissivity);

% Ensure alpha is 0 to 180 (Check just in case)
if max(alpha_grid) > pi + 1e-5
    warning('Alpha grid seems to exceed 180 degrees. Visualizer assumes 0-pi.');
end

%% --- 2. Setup Figure and Layout ---
fig = figure('Name', 'Bremsstrahlung Interactive Viewer', ...
             'Color', 'w', 'Position', [100, 100, 1000, 600]);

% Layout: Left = Spectrum, Right = Anisotropy Pattern, Bottom = Controls

% Left Plot (Spectrum): Standard Cartesian Axes
ax_spec = axes('Parent', fig, 'Position', [0.08, 0.4, 0.4, 0.5]);

% Right Plot (Radiation Pattern): Polar Axes (Specific fix here)
ax_pat  = polaraxes('Parent', fig, 'Position', [0.55, 0.4, 0.35, 0.5]); 

% --- 3. Initial Indices (Start from middle) ---
idx_v = round(Nv/2);
idx_t = round(Nt/2);
idx_a = round(Na/2);

%% --- 4. Create Sliders ---
% UI Controls Position: [left bottom width height]

% Slider 1: Velocity (v)
lbl_v = uicontrol('Style', 'text', 'Position', [100, 130, 300, 20], ...
    'String', '', 'BackgroundColor', 'w', 'FontSize', 10, 'HorizontalAlignment', 'left');
sld_v = uicontrol('Style', 'slider', 'Position', [100, 110, 300, 20], ...
    'Min', 1, 'Max', Nv, 'Value', idx_v, 'SliderStep', [1/(Nv-1), 1/(Nv-1)], ...
    'Callback', @updatePlots);

% Slider 2: Pitch Angle (theta)
lbl_t = uicontrol('Style', 'text', 'Position', [100, 80, 300, 20], ...
    'String', '', 'BackgroundColor', 'w', 'FontSize', 10, 'HorizontalAlignment', 'left');
sld_t = uicontrol('Style', 'slider', 'Position', [100, 60, 300, 20], ...
    'Min', 1, 'Max', Nt, 'Value', idx_t, 'SliderStep', [1/(Nt-1), 1/(Nt-1)], ...
    'Callback', @updatePlots);

% Slider 3: Observation Angle (alpha)
% Note: Alpha is 0 to 180 degrees
lbl_a = uicontrol('Style', 'text', 'Position', [550, 130, 300, 20], ...
    'String', '', 'BackgroundColor', 'w', 'FontSize', 10, 'HorizontalAlignment', 'left');
sld_a = uicontrol('Style', 'slider', 'Position', [550, 110, 300, 20], ...
    'Min', 1, 'Max', Na, 'Value', idx_a, 'SliderStep', [1/(Na-1), 1/(Na-1)], ...
    'Callback', @updatePlots);

% Plot Description
uicontrol('Style', 'text', 'Position', [550, 60, 350, 40], ...
    'String', {'Left Plot: Spectrum P(\omega) for selected \alpha', ...
               'Right Plot: Radiation Pattern (Dependence on \alpha)'}, ...
    'BackgroundColor', 'w', 'FontSize', 9, 'HorizontalAlignment', 'left');

% Store data in figure appdata to access in callbacks
guidata(fig, struct('LUT', LUT_Emissivity, ...
                    'w', w_grid, 'ag', alpha_grid, 'tg', theta_p_grid, 'vg', v_grid, ...
                    'ax_spec', ax_spec, 'ax_pat', ax_pat, ...
                    'lbl_v', lbl_v, 'lbl_t', lbl_t, 'lbl_a', lbl_a, ...
                    'sld_v', sld_v, 'sld_t', sld_t, 'sld_a', sld_a));

% Trigger initial update
updatePlots(fig, []);

%% --- 5. Update Callback Function ---
function updatePlots(src, ~)
    % Get Data
    if isa(src, 'matlab.ui.Figure')
        hObj = src;
    else
        hObj = get(src, 'Parent'); % If slider called, get parent figure
    end
    data = guidata(hObj);
    
    % Get Slider Values (Round to nearest integer index)
    iv = round(get(data.sld_v, 'Value'));
    it = round(get(data.sld_t, 'Value'));
    ia = round(get(data.sld_a, 'Value'));
    
    % Update Labels
    v_val = data.vg(iv);
    t_val_deg = rad2deg(data.tg(it));
    a_val_deg = rad2deg(data.ag(ia));
    
    set(data.lbl_v, 'String', sprintf('Velocity v: %.2e m/s (Idx: %d)', v_val, iv));
    set(data.lbl_t, 'String', sprintf('Pitch Angle \\theta_p: %.1f deg (Idx: %d)', t_val_deg, it));
    set(data.lbl_a, 'String', sprintf('Obs Angle \\alpha: %.1f deg (Idx: %d)', a_val_deg, ia));
    
    % --- Plot 1: Spectrum (Log-Log) ---
    % Plots Emissivity vs Frequency for the specific sliders (v, theta, alpha)
    axes(data.ax_spec);
    spectrum = data.LUT(:, ia, it, iv);
    
    loglog(data.w, spectrum, 'b-', 'LineWidth', 2);
    grid on;
    xlabel('Frequency \omega [rad/s]');
    ylabel('Emissivity j_{\omega, \Omega}');
    title(sprintf('Spectrum @ \\alpha=%.0f^\\circ', a_val_deg));
    
    % Add cutoff line for reference
    E_kin = 0.5 * 9.109e-31 * v_val^2;
    hbar = 1.054e-34;
    w_cutoff = E_kin / hbar;
    xline(w_cutoff, 'r--', 'Label', 'Cutoff');
    
    % --- Plot 2: Radiation Pattern (Polar) ---
    % Plots Emissivity vs Alpha for the selected frequency (middle of log range) and (v, theta)
    % We pick a frequency below cutoff to see the pattern
    w_idx_plot = find(data.w < w_cutoff, 1, 'first');
    if isempty(w_idx_plot), w_idx_plot = 1; end
    
    % Extract pattern for 0-180 degrees
    pattern_data = squeeze(data.LUT(w_idx_plot, :, it, iv)); 
    
    % Mirror for 360 visualization (Optional, but helps see "Donut/8-shape")
    % Data is 0 to pi. We append pi to 2pi.
    alpha_plot = [data.ag, data.ag + pi];
    pattern_plot = [pattern_data, pattern_data]; 
    
    % Sort for correct line connecting
    [alpha_sorted, sort_idx] = sort(alpha_plot);
    rad_sorted = pattern_plot(sort_idx);
    
    % Clear previous polar plot but keep the object
    cla(data.ax_pat);
    
    % Use polarplot on the specific polar axes object
    polarplot(data.ax_pat, alpha_sorted, rad_sorted, 'r-', 'LineWidth', 2);
    hold(data.ax_pat, 'on');
    
    % Add a marker for the current Slider Alpha
    polarplot(data.ax_pat, [data.ag(ia), data.ag(ia)], [0, max(rad_sorted)], 'b--', 'LineWidth', 2);
    
    title(data.ax_pat, sprintf('Radiation Pattern (\\omega=%.1e)\nBlue line = Current Slider', data.w(w_idx_plot)));
    rlim(data.ax_pat, [0, max(rad_sorted)*1.1]);
    thetaticks(data.ax_pat, 0:45:315);
end